SocialInitiatives2/Controllers/IndexController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Social_Initiatives.Controllers
{

    [Route("")]
    [Route("[controller]/[action]")]
    public class IndexController : Controller
    {

        public IActionResult Home()
        {
            ViewBag.SelectedNav = "Home";
            return View();
        }
    }
}

SocialInitiatives2/Views/Shared/_Layouts.cshtml
@model RegisterModel

<!DOCTYPE html>
<html>
<head>
    <!-- inside <head> -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    @*<link href="/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <link href="~/Views/Shared/main.css" rel="stylesheet" />
        <script src="~/lib/popper.js/dist/umd/popper.js"></script>*@
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <link href="~/CustomCSS/main.css" rel="stylesheet" />
</head>
<body>
    <!-- NavBar -->
    <div class="container-fluid" style="padding-left:0; padding-right:0">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="@Url.Action("Home", "Index")">
                <img src="~/Images/NavBar/Screen Shot 2018-07-01 at 3.40.33 PM.png" style="height:4vh;width:4vw;" />
                <img src="~/Images/NavBar/TSRS logo.jpg" style="height:4vh;width:4vw;" />
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div id="navbarNavDropdown" class="navbar-collapse collapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item @(ViewBag.SelectedNav == "Home" ? "active" : "") ">
                        <a class="nav-link" href="@Url.Action("Home","Index")">Home @if(ViewBag.SelectedNav == "Home") {<span class="sr-only">(current)</span>}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Calendar</a>
                    </li>
                    <li class="nav-item @(ViewBag.SelectedNav == "Initiatives" ? "active" : "") ">
                        <a class="nav-link" href="@Url.Action("Index","Initiatives")">Initiatives @if (ViewBag.SelectedNav == "Initiatives")
                        {<span class="sr-only">(current)</span>}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Start your own Initiative</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Club</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Gallery</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contact Us</a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    @if (!User.Identity.IsAuthenticated)
                    {

                        <li class="nav-item">
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#loginModal">Login</button>
                        </li>

                    }
                    else
                    {
                        <li class="nav-item">
                            <button onclick="location.href='@Url.Action("LogOut", "Account")'" class="nav-link btn-primary"> Logout </button>
                        </li>
                    }
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#registerModal">Register</button>
                        </li>
                    }
                </ul>
            </div>
        </nav>
    </div>
    <!-- Modal Popup for Register -->
    <div class="modal fade" id="registerModal" tabindex="-1" role="dialog" aria-labelledby="registerModallabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form asp-action="Register" asp-controller="Account" method="post">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="registerModalLabel">Modal title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">

                        <input type="hidden" asp-for="ReturnUrl" />
                        <div class="form-group">
                            <label asp-for="Name">User Name</label>
                            <input type="text" class="form-control" placeholder="Enter your name"
                                   asp-for="Name" />
                        </div>
                        <div class="form-group">
                            <label asp-for="Email">Email address</label>
                            <input type="email" class="form-control" aria-describedby="emailHelp" placeholder="Enter email" asp-for="Email" />
                        </div>
                        <div class="form-group">
                            <label asp-for="Password">Password</label>
                            <input type="password" class="form-control" asp-for="Password" placeholder="Password">
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Register</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- Modal Popup for Login -->
    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModallabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form asp-action="Login" asp-controller="Account" method="post">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="loginModalLabel">Modal title</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <input type="hidden" asp-for="ReturnUrl" />
                        <div class="form-group">
                            <label asp-for="Email">Email address</label>
                            <input type="email" class="form-control" aria-describedby="emailHelp" placeholder="Enter email" asp-for="Email" />
                        </div>
                        <div class="form-group">
                            <label asp-for="Password">Password</label>
                            <input type="password" class="form-control" asp-for="Password" placeholder="Password">
                        </div>

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Login</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

    @RenderBody()
</body>
</html>